/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_B78sn82ah",
    "aws_user_pools_web_client_id": "2tagf6nq0mr3hau8n8t4mbimhe",
    "oauth": {
        "domain": "amplifyreactcustauth-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        // "redirectSignIn": "http://localhost:3000/",
        // "redirectSignOut": "http://localhost:3000/",
        "redirectSignIn": "https://appclient2.aws-amplify.dev/",
        "redirectSignOut": "https://appclient2.aws-amplify.dev/",
        "responseType": "code"
    },
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apitest",
            "endpoint": "https://wv7ikdzd0h.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
